Sprint 2
KudrinMatvey/middle.messenger.praktikum.yandex pull request #3
Opened 2021-10-29 17:57 UTC by KudrinMatvey

2021-10-31 10:17 UTC, evgenygil requested changes
Необходимо реализовать класс для HTTP запросов

2021-10-31 10:17 UTC, evgenygil commented on src/components/button/button.ts
>  export interface ButtonConfig {
Возможно не обязательно экспортировать этот интерфейс, если он уже лежит рядом и используется только тут, либо вынести его в отдельный файл, и тогда экспорт оправдан

2021-10-31 10:17 UTC, evgenygil commented on src/components/button/button.ts
> +  onClick?: () => any;
Почему `any`, мне кажется обычно `onClick` не возвращает ничего, то есть `void`

2021-10-31 10:17 UTC, evgenygil commented on src/components/input/input.module.scss
> +.inputField {
А чем обусловлен переход на кэмелкейс?

2021-10-31 10:17 UTC, evgenygil commented on src/components/input/input.module.scss.d.ts
> +export const errorMessage: string;
Нет необходимости хранить d.ts ы в репозитории в коде

2021-10-31 10:17 UTC, evgenygil commented on src/components/input/input.ts
> +    return false;
Почему всегда возвращается `false`?

2021-10-31 10:17 UTC, evgenygil commented on src/components/link/link.ts
> +    super.componentDidRender();
В компонентах выше нигде не видел, чтобы выполнялась эта конструкция, это специально тут или в остальных наследниках Блока все таки она нужна?

2021-10-31 10:17 UTC, evgenygil commented on src/components/link/link.ts
> +    return [styles.linkWrapper, this.props.className].filter(Boolean).join(' ');
Возможно стоит вынести это в отдельную функцию, которая будет принимать массив, типа getClassNames, чтобы не писать `.filter(Boolean).join(' ')` в каждом классе, не критикал

2021-10-31 10:17 UTC, evgenygil commented on src/components/shared/block.ts
> +  private _meta: {tagName: string; props: Props; display: 'block' | 'inline-block' | 'inline'};
Хорошо, когда методы выстроены согласно модификаторам доступа, например сначала `private`, потом `protected`, потом `public`, здесь они немного перемешаны

2021-10-31 10:17 UTC, evgenygil commented on src/modules/chats/page/chats.page.ts
> +        {
Вот это стоит унести в какой-то mock-файл, чтобы не хранить в исполняемом классе столько текста

2021-10-31 10:17 UTC, evgenygil commented on src/modules/profile/profile/profile.page.ts
> +  buildChildren(): ProfilePageChildren {
Логически тут было бы понятнее, если наверное это все называлось формой, ну т.е. отделить саму форму непосредственно отсюда и остальной контент страницы

2021-10-31 10:17 UTC, evgenygil commented on src/utils/initialize-form.ts
> +    event.stopPropagation();
Не очень понятно зачем здесь останавливать распостранение..

2021-10-31 10:17 UTC, evgenygil commented on src/utils/initialize-form.ts
> +      .reduce((prev: Boolean, child: { validate?: () => boolean }) => prev && child?.validate?.(), true);
По идее тут можно вместо 2 циклов (фильтр и редьюс) сделать все в редьюсе

2021-10-31 10:17 UTC, evgenygil commented on src/components/shared/block.ts
> +  constructor(tagName = 'div', props = {} as Props, display: 'block' | 'inline-block' | 'inline' = 'block') {
Тоже можно убрать в отдельный тип

2021-10-31 10:17 UTC, evgenygil commented on src/modules/profile/profile/index.ts
> +registerDefaultValueHelper();
Это можно убрать куда-то на уровень выше, чтобы не вызывать в каждом файле?

2021-10-31 10:17 UTC, evgenygil commented on src/modules/profile/profile/profile.page.ts
> +export class ProfilePage extends Page<ProfilePageProps, ProfilePageChildren> {
`/profile/profile/profile.page.ts` выглядит немного странно, 3х слово profile, как раз может поделить на форму редактирования и тп

2021-10-31 11:53 UTC, KudrinMatvey commented on src/components/input/input.module.scss
> +.inputField {
Я в этом спринте перешел на scss modules
Никак не мог заставить его работать по-нормальному с постцсс конфигом (чтобы он сам переименовывал классы в камелкейс)
Так что пришлось ручками

2021-10-31 11:54 UTC, KudrinMatvey commented on src/components/input/input.module.scss
> +.inputField {
А по дефолту парсель генерирует классы для .module.scss не переименовывая

2021-10-31 21:15 UTC, KudrinMatvey commented on src/utils/initialize-form.ts
> +    event.stopPropagation();
Сделано для того чтобы проверять на валидность все элементы формы, но сабмит делать только для тех у которых есть нейм
просто 2 раза чтоб не собирать)

2021-10-31 21:21 UTC, KudrinMatvey commented on src/components/shared/block.ts
> +  private _meta: {tagName: string; props: Props; display: 'block' | 'inline-block' | 'inline'};
Добавил линт правило на это

2021-10-31 21:25 UTC, KudrinMatvey commented
> Необходимо реализовать класс для HTTP запросов

Почему-то не сохранился \ закомиттился
Сейчас добавил!

2021-10-31 21:26 UTC, KudrinMatvey commented on src/modules/profile/profile/index.ts
> +registerDefaultValueHelper();
Потенциально уберу в точку входа приложения когда будем роутинг делать
Есть идея убрать в метод рендер, но тогда надо будет туда передавать конструктор\ функцию для получения инстанса пейдж обьекта

2021-10-31 21:27 UTC, KudrinMatvey commented on src/components/shared/block.ts
> +  constructor(tagName = 'div', props = {} as Props, display: 'block' | 'inline-block' | 'inline' = 'block') {
сделано

2021-10-31 21:27 UTC, KudrinMatvey commented on src/components/link/link.ts
> +    super.componentDidRender();
убрал

2021-10-31 21:27 UTC, KudrinMatvey commented on src/components/button/button.ts
>  export interface ButtonConfig {
оставил локальным

2021-10-31 21:28 UTC, KudrinMatvey commented on src/utils/initialize-form.ts
> +    event.stopPropagation();
убрал

2021-10-31 21:28 UTC, KudrinMatvey commented on src/modules/profile/profile/profile.page.ts
> +export class ProfilePage extends Page<ProfilePageProps, ProfilePageChildren> {
переименовал

2021-10-31 21:28 UTC, KudrinMatvey commented on src/components/link/link.ts
> +    return [styles.linkWrapper, this.props.className].filter(Boolean).join(' ');
Сделано для того чтобы проверять на валидность все элементы формы, но сабмит делать только для тех у которых есть нейм
просто 2 раза чтоб не собирать)

2021-11-01 08:16 UTC, evgenygil approved these changes
Привет, ну в целом ок

2021-11-01 08:16 UTC, evgenygil commented on src/components/input/input.module.scss
> +.inputField {
Ясно, не очень хорошо ему подчинятся кмк, любая либа может навязывать свои правила, и менять из-за нее кодовую базу не всегда целесообразно. На данном этапе ок

2021-11-01 08:16 UTC, evgenygil commented on src/utils/http.ts
> +// for use in node js need this package
Думаю тут это необязательно

2021-11-01 08:16 UTC, evgenygil commented on src/utils/http.ts
> +      xhr.timeout = timeout ?? 0;
Думаю тут можно поставить что-то больше 0, а то получается без таймаута вообще?

2021-11-01 08:16 UTC, evgenygil commented on src/utils/http.ts
> +          resolve(xhr);
В обработке исключения разве не reject?

2021-11-14 11:08 UTC, merged